package com.cfao.app.beans;

import javafx.beans.property.ListProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleListProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;

import javax.persistence.*;
import java.util.List;
import java.util.Set;

import static javax.persistence.GenerationType.AUTO;

/**
 * EtatFormation generated by hbm2java
 */
@Entity
@Table(name="etat_formation"
)
public class EtatFormation  implements java.io.Serializable {


    private SimpleIntegerProperty idetatformation = new SimpleIntegerProperty();
    private SimpleStringProperty libelle = new SimpleStringProperty();
    private ListProperty<Formation> formations = new SimpleListProperty<>();

    public EtatFormation() {
    }


    public EtatFormation(String libelle) {
        this.libelle.set(libelle);
    }
    public EtatFormation(String libelle, Set<Formation> formationses) {
        this.libelle.set(libelle);
        this.formations.set(formations);
    }

    @Id @GeneratedValue(strategy=AUTO)
    @Column(name="IDETATFORMATION", unique=true, nullable=false)
    public Integer getIdetatformation() {
        return this.idetatformation.get();
    }

    public void setIdetatformation(Integer idetatformation) {
        this.idetatformation.set(idetatformation);
    }


    @Column(name="LIBELLE", nullable=false, length=50)
    public String getLibelle() {
        return this.libelle.get();
    }

    public void setLibelle(String libelle) {
        this.libelle.set(libelle);
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="etatFormation")
    public List<Formation> getFormations() {
        return this.formations;
    }

    public void setFormations(List<Formation> formations) {
        this.formations.set(FXCollections.observableArrayList(formations));
    }

    @Override
    public String toString() {
        return getLibelle();
    }
}


