package com.cfao.app.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated Aug 9, 2017 5:49:15 PM by Hibernate Tools 4.3.1

/**
 * LangueParleeId generated by hbm2java
 */
@Embeddable
public class FormationPersonneId implements java.io.Serializable {

    private int formation;
    private int personne;

    public FormationPersonneId() {
    }

    public FormationPersonneId(int formation, int personne) {
        this.personne = personne;
        this.formation = formation;
    }


    @Column(name = "PERSONNE", nullable = false)
    public int getPersonne() {
        return this.personne;
    }

    public void setPersonne(int personne) {
        this.personne = personne;
    }


    @Column(name = "FORMATION", nullable = false)
    public int getFormation() {
        return this.formation;
    }

    public void setFormation(int formation) {
        this.formation = formation;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof LangueParleeId)) return false;
        FormationPersonneId castOther = (FormationPersonneId) other;

        return (this.getPersonne() == castOther.getPersonne())
                && (this.getFormation() == castOther.getFormation());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPersonne();
        result = 37 * result + this.getFormation();
        return result;
    }


}


