package com.cfao.app.beans;
// Generated Aug 9, 2017 5:49:15 PM by Hibernate Tools 4.3.1


        import javax.persistence.AttributeOverride;
        import javax.persistence.AttributeOverrides;
        import javax.persistence.Column;
        import javax.persistence.EmbeddedId;
        import javax.persistence.Entity;
        import javax.persistence.FetchType;
        import javax.persistence.JoinColumn;
        import javax.persistence.ManyToOne;
        import javax.persistence.Table;

/**
 * LangueParlee generated by hbm2java
 */
@Entity
@Table(name="langue_parlee"
)
public class LangueParlee  implements java.io.Serializable {


    private LangueParleeId id;
    private Langue langue;
    private Personne personne;

    public LangueParlee() {
    }

    public LangueParlee(LangueParleeId id, Langue langue, Personne personne) {
        this.id = id;
        this.langue = langue;
        this.personne = personne;
    }

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="personne", column=@Column(name="PERSONNE", nullable=false) ),
            @AttributeOverride(name="langue", column=@Column(name="LANGUE", nullable=false) ) } )
    public LangueParleeId getId() {
        return this.id;
    }

    public void setId(LangueParleeId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LANGUE", nullable=false, insertable=false, updatable=false)
    public Langue getLangue() {
        return this.langue;
    }

    public void setLangue(Langue langue) {
        this.langue = langue;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSONNE", nullable=false, insertable=false, updatable=false)
    public Personne getPersonne() {
        return this.personne;
    }

    public void setPersonne(Personne personne) {
        this.personne = personne;
    }




}


