package com.cfao.app.beans;

// Generated Aug 9, 2017 5:49:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LangueParleeId generated by hbm2java
 */
@Embeddable
public class LangueParleeId implements java.io.Serializable {


    private int personne;
    private int langue;

    public LangueParleeId() {
    }

    public LangueParleeId(int personne, int langue) {
        this.personne = personne;
        this.langue = langue;
    }


    @Column(name = "PERSONNE", nullable = false)
    public int getPersonne() {
        return this.personne;
    }

    public void setPersonne(int personne) {
        this.personne = personne;
    }


    @Column(name = "LANGUE", nullable = false)
    public int getLangue() {
        return this.langue;
    }

    public void setLangue(int langue) {
        this.langue = langue;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof LangueParleeId)) return false;
        LangueParleeId castOther = (LangueParleeId) other;

        return (this.getPersonne() == castOther.getPersonne())
                && (this.getLangue() == castOther.getLangue());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPersonne();
        result = 37 * result + this.getLangue();
        return result;
    }


}


