package com.cfao.app.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonneCompetenceId generated by hbm2java
 */
@Embeddable
public class PersonneCompetenceId  implements java.io.Serializable {


    private int personne;
    private int competence;
    public PersonneCompetenceId() {
    }


    public PersonneCompetenceId(int personne, int competence) {
        this.personne = personne;
        this.competence = competence;
    }



    @Column(name="PERSONNE", nullable=false)
    public int getPersonne() {
        return this.personne;
    }

    public void setPersonne(int personne) {
        this.personne = personne;
    }


    @Column(name="COMPETENCE", nullable=false)
    public int getCompetence() {
        return this.competence;
    }

    public void setCompetence(int competence) {
        this.competence = competence;
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof PersonneCompetenceId) ) return false;
        PersonneCompetenceId castOther = ( PersonneCompetenceId ) other;

        return (this.getPersonne()==castOther.getPersonne())
                && (this.getCompetence()==castOther.getCompetence());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPersonne();
        result = 37 * result + this.getCompetence();

        return result;
    }


    @Override
    public String toString() {
        return "PersonneCompetenceId{" +
                "personne=" + personne +
                ", competence=" + competence +
                "}\n";
    }
}


