package com.cfao.app.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonneCompetenceId generated by hbm2java
 */
@Embeddable
public class PersonneCompetenceId  implements java.io.Serializable {


    private int personne;
    private int competence;
    private String certification;
    private Integer formation;

    public PersonneCompetenceId() {
    }


    public PersonneCompetenceId(int personne, int competence, String certification) {
        this.personne = personne;
        this.competence = competence;
        this.certification = certification;
    }
    public PersonneCompetenceId(int personne, int competence, String certification, Integer formation) {
        this.personne = personne;
        this.competence = competence;
        this.certification = certification;
        this.formation = formation;
    }



    @Column(name="PERSONNE", nullable=false)
    public int getPersonne() {
        return this.personne;
    }

    public void setPersonne(int personne) {
        this.personne = personne;
    }


    @Column(name="COMPETENCE", nullable=false)
    public int getCompetence() {
        return this.competence;
    }

    public void setCompetence(int competence) {
        this.competence = competence;
    }


    @Column(name="CERTIFICATION", nullable=false, length=2)
    public String getCertification() {
        return this.certification;
    }

    public void setCertification(String certification) {
        this.certification = certification;
    }


    @Column(name="FORMATION")
    public Integer getFormation() {
        return this.formation;
    }

    public void setFormation(Integer formation) {
        this.formation = formation;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof PersonneCompetenceId) ) return false;
        PersonneCompetenceId castOther = ( PersonneCompetenceId ) other;

        return (this.getPersonne()==castOther.getPersonne())
                && (this.getCompetence()==castOther.getCompetence())
                && ( (this.getCertification()==castOther.getCertification()) || ( this.getCertification()!=null && castOther.getCertification()!=null && this.getCertification().equals(castOther.getCertification()) ) )
                && ( (this.getFormation()==castOther.getFormation()) || ( this.getFormation()!=null && castOther.getFormation()!=null && this.getFormation().equals(castOther.getFormation()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPersonne();
        result = 37 * result + this.getCompetence();
        result = 37 * result + ( getCertification() == null ? 0 : this.getCertification().hashCode() );
        result = 37 * result + ( getFormation() == null ? 0 : this.getFormation().hashCode() );
        return result;
    }


}


