package com.cfao.app.beans;

import javafx.beans.property.ListProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleListProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;

import javax.persistence.*;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Personnels generated by hbm2java
 */
@Entity
@Table(name="personnels"
)
public class Personnel implements java.io.Serializable {


    private SimpleIntegerProperty idpersonnel = new SimpleIntegerProperty();
    private SimpleStringProperty nom = new SimpleStringProperty();
    private SimpleStringProperty prenom = new SimpleStringProperty();
    private SimpleStringProperty adresse = new SimpleStringProperty();
    private SimpleStringProperty telephone = new SimpleStringProperty();
    private ListProperty<Formation> formations = new SimpleListProperty<>();
    private ListProperty<Domaine> domaines = new SimpleListProperty<>();

    public Personnel() {
    }


    public Personnel(String nom) {
        this.nom.set(nom);
    }
    public Personnel(String nom, String prenom, String adresse, String telephone, List<Formation> formations) {
        this.nom.set(nom);
        this.prenom.set(prenom);
        this.adresse.set(adresse);
        this.telephone.set(telephone);
        this.formations.set(FXCollections.observableArrayList(formations));
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="IDPERSONNEL", unique=true, nullable=false)
    public Integer getIdpersonnel() {
        return this.idpersonnel.get();
    }

    public void setIdpersonnel(Integer idpersonnel) {
        this.idpersonnel.set(idpersonnel);
    }


    @Column(name="NOM", nullable=false, length=30)
    public String getNom() {
        return this.nom.get();
    }

    public void setNom(String nom) {
        this.nom.set(nom);
    }


    @Column(name="PRENOM", length=30)
    public String getPrenom() {
        return this.prenom.get();
    }

    public void setPrenom(String prenom) {
        this.prenom.set(prenom);
    }


    @Column(name="ADRESSE", length=50)
    public String getAdresse() {
        return this.adresse.get();
    }

    public void setAdresse(String adresse) {
        this.adresse.set(adresse);
    }


    @Column(name="TELEPHONE", length=20)
    public String getTelephone() {
        return this.telephone.get();
    }

    public void setTelephone(String telephone) {
        this.telephone.set(telephone);
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="formateurs",  joinColumns = {
            @JoinColumn(name="PERSONNEL", nullable=false, updatable=false) }, inverseJoinColumns = {
            @JoinColumn(name="FORMATION", nullable=false, updatable=false) })
    public List<Formation> getFormations() {
        return this.formations;
    }

    public void setFormations(List<Formation> formations) {
        this.formations.set(FXCollections.observableArrayList(formations));
    }


    @Override
    public String toString() {
        return getNom() + " " + getPrenom();
    }

    @ManyToMany(fetch=FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name="personnel_domaine", joinColumns = {
            @JoinColumn(name="PERSONNEL", nullable=false, updatable=false) }, inverseJoinColumns = {
            @JoinColumn(name="DOMAINE", nullable=false, updatable=false) })
    public List<Domaine> getDomaines() {
        return domaines.get();
    }

    public ListProperty<Domaine> domainesProperty() {
        return domaines;
    }

    public void setDomaines(List<Domaine> domaines) {
        this.domaines.set(FXCollections.observableArrayList(domaines));
    }
}


