package com.cfao.app.beans;


import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.math.BigDecimal;

/**
 * PersonneQcmId generated by hbm2java
 */
@Embeddable
public class PersonneQcmId implements java.io.Serializable {


    private int personne;
    private int qcm;
    private BigDecimal note;

    public PersonneQcmId() {
    }

    public PersonneQcmId(int personne, int qcm, BigDecimal note) {
        this.personne = personne;
        this.qcm = qcm;
        this.note = note;
    }


    @Column(name = "PERSONNE", nullable = false)
    public int getPersonne() {
        return this.personne;
    }

    public void setPersonne(int personne) {
        this.personne = personne;
    }


    @Column(name = "QCM", nullable = false)
    public int getQcm() {
        return this.qcm;
    }

    public void setQcm(int qcm) {
        this.qcm = qcm;
    }


    @Column(name = "NOTE", nullable = false, precision = 6)
    public BigDecimal getNote() {
        return this.note;
    }

    public void setNote(BigDecimal note) {
        this.note = note;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof PersonneQcmId)) return false;
        PersonneQcmId castOther = (PersonneQcmId) other;

        return (this.getPersonne() == castOther.getPersonne())
                && (this.getQcm() == castOther.getQcm())
                && ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null && this.getNote().equals(castOther.getNote())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPersonne();
        result = 37 * result + this.getQcm();
        result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
        return result;
    }


    @Override
    public String toString() {
        return "PersonneQcmId{" +
                "personne=" + personne +
                ", qcm=" + qcm +
                ", note=" + note +
                '}';
    }
}


