package com.cfao.app.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProfilPersonneId generated by hbm2java
 */
@Embeddable
public class ProfilPersonneId  implements java.io.Serializable {


    private int personne;
    private int profil;
    private int niveau;

    public ProfilPersonneId() {
    }

    public ProfilPersonneId(int personne, int profil, int niveau) {
        this.personne = personne;
        this.profil = profil;
        this.niveau = niveau;
    }



    @Column(name="PERSONNE", nullable=false)
    public int getPersonne() {
        return this.personne;
    }

    public void setPersonne(int personne) {
        this.personne = personne;
    }


    @Column(name="PROFIL", nullable=false)
    public int getProfil() {
        return this.profil;
    }

    public void setProfil(int profil) {
        this.profil = profil;
    }


    @Column(name="NIVEAU", nullable=false)
    public int getNiveau() {
        return this.niveau;
    }

    public void setNiveau(int niveau) {
        this.niveau = niveau;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof ProfilPersonneId) ) return false;
        ProfilPersonneId castOther = ( ProfilPersonneId ) other;

        return (this.getPersonne()==castOther.getPersonne())
                && (this.getProfil()==castOther.getProfil())
                && (this.getNiveau()==castOther.getNiveau());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPersonne();
        result = 37 * result + this.getProfil();
        result = 37 * result + this.getNiveau();
        return result;
    }


}


