package com.cfao.app.beans;

import javafx.beans.property.SetProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleSetProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableSet;
import org.hibernate.annotations.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Profils generated by hbm2java
 */
@Entity
@Table(name = "profils"
        , catalog = "servicepro"
)
public class Profil implements java.io.Serializable {


    private SimpleIntegerProperty idprofil = new SimpleIntegerProperty();
    private SimpleStringProperty abbreviation = new SimpleStringProperty();
    private SimpleStringProperty libelle = new SimpleStringProperty();
    private SetProperty<Competence> competences = new SimpleSetProperty<>();
    private SetProperty<ProfilPersonne> profilPersonnes = new SimpleSetProperty<>();

    public Profil() {
    }


    public Profil(String libelle) {
        this.libelle.set(libelle);
    }

    public Profil(String abbreviation, String libelle, Set<Competence> competences, Set<ProfilPersonne> profilPersonne) {
        this.abbreviation.set(abbreviation);
        this.libelle.set(libelle);
        this.competences.set(FXCollections.observableSet(competences));
        this.profilPersonnes.set(FXCollections.observableSet(profilPersonne));
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)


    @Column(name = "IDPROFIL", unique = true, nullable = false)
    public Integer getIdprofil() {
        return this.idprofil.get();
    }

    public void setIdprofil(Integer idprofil) {
        this.idprofil.set(idprofil);
    }


    @Column(name = "ABBREVIATION", length = 15)
    public String getAbbreviation() {
        return this.abbreviation.get();
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation.set(abbreviation);
    }


    @Column(name = "LIBELLE", nullable = false, length = 50)
    public String getLibelle() {
        return this.libelle.get();
    }

    public void setLibelle(String libelle) {
        this.libelle.set(libelle);
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "profil", cascade = CascadeType.ALL)
    public Set<ProfilPersonne> getProfilPersonnes() {
        return this.profilPersonnes.get();
    }

    public void setProfilPersonnes(Set<ProfilPersonne> profilPersonne) {
       this.profilPersonnes.set(FXCollections.observableSet(profilPersonne));
    }


    public SimpleStringProperty libelleProperty() {
        return libelle;
    }


    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "profil_competence", catalog = "servicepro", joinColumns = {
            @JoinColumn(name = "PROFIL", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "COMPETENCE", nullable = false, updatable = false)})
    public Set<Competence> getCompetences() {
        return competences.get();
    }

    public SetProperty<Competence> competencesProperty() {
        return competences;
    }

    public void setCompetences(Set<Competence> competences) {
        this.competences.set(FXCollections.observableSet(competences));
    }
    @Transient
    public Competence getOriginalCompetence(Competence competence){
        for(Competence original : this.competences){
            if(original.getIdcompetence().equals(competence.getIdcompetence()))
                return original;
        }
        return null;
    }
}


