package com.cfao.app.beans;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * QcmType generated by hbm2java
 */
@Entity
@Table(name = "qcm_type"
        , catalog = "servicepro"
)
public class QcmType implements java.io.Serializable {


    private Integer idqcmtype;
    private String libelle;
    private Set<Qcm> qcms = new HashSet<Qcm>(0);

    public QcmType() {
    }


    public QcmType(String libelle) {
        this.libelle = libelle;
    }

    public QcmType(String libelle, Set<Qcm> qcms) {
        this.libelle = libelle;
        this.qcms = qcms;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "IDQCMTYPE", unique = true, nullable = false)
    public Integer getIdqcmtype() {
        return this.idqcmtype;
    }

    public void setIdqcmtype(Integer idqcmtype) {
        this.idqcmtype = idqcmtype;
    }


    @Column(name = "LIBELLE", nullable = false, length = 30)
    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "qcmType")
    public Set<Qcm> getQcms() {
        return this.qcms;
    }

    public void setQcms(Set<Qcm> qcms) {
        this.qcms = qcms;
    }

    @Override
    public String toString() {
        return libelle;
    }
}


