package com.cfao.app.beans;

// Generated Aug 29, 2017 3:29:44 AM by Hibernate Tools 4.3.1


        import javafx.beans.property.*;
        import javafx.collections.FXCollections;

import javax.persistence.*;
import java.util.List;
import java.util.Set;

import static javax.persistence.GenerationType.AUTO;

/**
 * Sujets generated by hbm2java
 */
@Entity
@Table(name="sujets"
)
public class Sujet implements java.io.Serializable {


    private IntegerProperty idsujet = new SimpleIntegerProperty();
    private StringProperty libelle = new SimpleStringProperty();
    private ListProperty<Planification> planifications = new SimpleListProperty<>();
    private ListProperty<PlanificationModele> planificationModeles = new SimpleListProperty<>();

    public Sujet() {
    }


    public Sujet(String libelle) {
        this.libelle.set(libelle);
    }
    public Sujet(String libelle, Set<Planification> planifications) {
        this.libelle.set(libelle);
        this.planifications.set(FXCollections.observableArrayList(planifications));
    }

    @Id @GeneratedValue(strategy=AUTO)
    @Column(name="IDSUJET", unique=true, nullable=false)
    public Integer getIdsujet() {
        return this.idsujet.get();
    }

    public void setIdsujet(Integer idsujet) {
        this.idsujet.set(idsujet);
    }


    @Column(name="LIBELLE", nullable=false, length=250)
    public String getLibelle() {
        return this.libelle.get();
    }

    public void setLibelle(String libelle) {
        this.libelle.set(libelle);
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="sujet")
    public List<Planification> getPlanifications() {
        return this.planifications.get();
    }

    public void setPlanifications(List<Planification> planifications) {
        this.planifications.set(FXCollections.observableArrayList(planifications));
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="sujet")
    public List<PlanificationModele> getPlanificationModeles() {
        return planificationModeles.get();
    }

    public void setPlanificationModeles(List<PlanificationModele> planificationModeles) {
        this.planificationModeles.set(FXCollections.observableArrayList(planificationModeles));
    }

    @Override
    public String toString(){
        return getLibelle();
    }
}


