package com.cfao.app.beans;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

import javax.persistence.*;

/**
 * SupportFormation generated by hbm2java
 */
@Entity
@Table(name = "support_competence"
)
public class SupportCompetence implements java.io.Serializable {


    private SupportCompetenceId id = new SupportCompetenceId();
    private ObjectProperty<Competence> competence = new SimpleObjectProperty<>();
    private ObjectProperty<Support> support = new SimpleObjectProperty<>();

    public SupportCompetence() {
    }

    public SupportCompetence(SupportCompetenceId id, Competence competence, Support support) {
        this.id = id;
        this.competence.set(competence);
        this.support.set(support);
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "support", column = @Column(name = "SUPPORT", nullable = false)),
            @AttributeOverride(name = "competence", column = @Column(name = "COMPETENCE", nullable = false))})
    public SupportCompetenceId getId() {
        return this.id;
    }

    public void setId(SupportCompetenceId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPETENCE", nullable=false, insertable=false, updatable=false)
    public Competence getCompetence() {
        return this.competence.get();
    }

    public void setCompetence(Competence competence) {
        this.competence.set(competence);
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUPPORT", nullable=false, insertable=false, updatable=false)
    public Support getSupport() {
        return this.support.get();
    }

    public void setSupport(Support support) {
        if (support != null) {
            this.support.set(support);
        }
    }

    @Override
    public String toString() {
        return "Support = " + support.toString() + ", Formation = " + competence.get().getDescription();
    }
}


