package com.cfao.app.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupportFormationId generated by hbm2java
 */
@Embeddable
public class SupportCompetenceId implements java.io.Serializable {


    private int support;
    private int competence;

    public SupportCompetenceId() {
    }

    public SupportCompetenceId(int support, int competence) {
        this.support = support;
        this.competence = competence;
    }


    @Column(name = "SUPPORT", nullable = false)
    public int getSupport() {
        return this.support;
    }

    public void setSupport(int support) {
        this.support = support;
    }


    @Column(name = "COMPETENCE", nullable = false)
    public int getCompetence() {
        return this.competence;
    }

    public void setCompetence(int competence) {
        this.competence = competence;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof SupportFormationId)) return false;
        SupportFormationId castOther = (SupportFormationId) other;

        return (this.getSupport() == castOther.getSupport())
                && (this.getCompetence() == castOther.getFormation());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSupport();
        result = 37 * result + this.getCompetence();
        return result;
    }


}


