package com.cfao.app.beans;
// Generated Sep 28, 2017 9:13:46 PM by Hibernate Tools 4.3.1


import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SupportCompetence generated by hbm2java
 */
@Entity
@Table(name = "support_competence"
)
public class SupportCompetence implements java.io.Serializable {


    private SimpleIntegerProperty idsupportcompetence = new SimpleIntegerProperty();
    private ObjectProperty<Competence> competence = new SimpleObjectProperty<>();
    private SimpleStringProperty code = new SimpleStringProperty();
    private SimpleStringProperty titre = new SimpleStringProperty();
    private SimpleStringProperty lien = new SimpleStringProperty();

    public SupportCompetence() {
    }


    public SupportCompetence(Competence competence, String titre, String lien) {
        this.competence.set(competence);
        this.titre.set(titre);
        this.lien.set(lien);
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "IDSUPPORTCOMPETENCE", unique = true, nullable = false)
    public Integer getIdsupportcompetence() {
        return this.idsupportcompetence.get();
    }

    public void setIdsupportcompetence(Integer idsupportcompetence) {
        this.idsupportcompetence.set(idsupportcompetence);
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COMPETENCE", nullable = false)
    public Competence getCompetence() {
        return this.competence.get();
    }

    public void setCompetence(Competence competence) {
        this.competence.set(competence);
    }

    @Column(name = "CODE", length = 50)
    public String getCode() {
        return this.code.get();
    }

    public void setCode(String code) {
        this.code.set(code);
    }


    @Column(name = "TITRE", nullable = false, length = 150)
    public String getTitre() {
        return this.titre.get();
    }

    public void setTitre(String titre) {
        this.titre.set(titre);
    }


    @Column(name = "LIEN", nullable = false, length = 150)
    public String getLien() {
        return this.lien.get();
    }

    public void setLien(String lien) {
        this.lien.set(lien);
    }


    public SimpleStringProperty titreProperty() {
        return titre;
    }

    public SimpleStringProperty codeProperty() {
        return code;
    }

    public SimpleStringProperty lienProperty() {
        return lien;
    }
}


