package com.cfao.app.beans;
// Generated Sep 28, 2017 9:13:46 PM by Hibernate Tools 4.3.1


import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SupportFormation generated by hbm2java
 */
@Entity
@Table(name="support_formation"
)
public class SupportFormation  implements java.io.Serializable {


    private SimpleIntegerProperty idsupportformation = new SimpleIntegerProperty();
    private ObjectProperty<Formation> formation = new SimpleObjectProperty<>();
    private SimpleStringProperty code = new SimpleStringProperty();
    private SimpleStringProperty titre = new SimpleStringProperty();
    private SimpleStringProperty lien = new SimpleStringProperty();

    public SupportFormation() {
    }


    public SupportFormation(Formation formation, String titre, String lien) {
        this.formation.set(formation);
        this.titre.set(titre);
        this.lien.set(lien);
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="IDSUPPORTFORMATION", unique=true, nullable=false)
    public Integer getIdsupportformation() {
        return this.idsupportformation.get();
    }

    public void setIdsupportformation(Integer idsupportformation) {
        this.idsupportformation.set(idsupportformation);
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FORMATION", nullable=false)
    public Formation getFormation() {
        return this.formation.get();
    }

    public void setFormation(Formation formation) {
        this.formation.set(formation);
    }


    @Column(name="CODE", length=50)
    public String getCode() {
        return this.code.get();
    }

    public void setCode(String code) {
        this.code.set(code);
    }


    @Column(name="TITRE", nullable=false, length=150)
    public String getTitre() {
        return this.titre.get();
    }

    public void setTitre(String titre) {
        this.titre.set(titre);
    }


    @Column(name="LIEN", nullable=false, length=150)
    public String getLien() {
        return this.lien.get();
    }

    public void setLien(String lien) {
        this.lien.set(lien);
    }


    public SimpleStringProperty codeProperty() {
        return code;
    }

    public SimpleStringProperty titreProperty() {
        return titre;
    }

    public SimpleStringProperty lienProperty() {
        return lien;
    }
}


