package com.cfao.app.beans;

import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
        ,catalog="servicepro"
)
public class User implements java.io.Serializable {


    private SimpleIntegerProperty iduser = new SimpleIntegerProperty();
    private SimpleStringProperty login = new SimpleStringProperty();
    private SimpleStringProperty password = new SimpleStringProperty();
    private int profile;

    public User() {
    }

    public User(String login, String password, int profile) {
        this.login.set(login);
        this.password.set(password);
        this.profile = profile;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="IDUSER", unique=true, nullable=false)
    public Integer getIduser() {
        return this.iduser.get();
    }

    public void setIduser(Integer iduser) {
        this.iduser.set(iduser);
    }


    @Column(name="LOGIN", nullable=false, length=30)
    public String getLogin() {
        return this.login.get();
    }

    public void setLogin(String login) {
        this.login.set(login);
    }


    @Column(name="PASSWORD", nullable=false, length=150)
    public String getPassword() {
        return this.password.get();
    }

    public void setPassword(String password) {
        this.password.set(password);
    }


    @Column(name="PROFILE", nullable=false)
    public int getProfile() {
        return this.profile;
    }

    public void setProfile(int profile) {
        this.profile = profile;
    }




}


