package com.cfao.app.beans;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
)
public class User implements java.io.Serializable {


    private SimpleIntegerProperty iduser = new SimpleIntegerProperty();
    private SimpleStringProperty login = new SimpleStringProperty();
    private SimpleStringProperty password = new SimpleStringProperty();
    private ObjectProperty<UserProfil> userProfil = new SimpleObjectProperty<>();

    public User() {
    }

    public User(String login, String password) {
        this.login.set(login);
        this.password.set(password);
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="IDUSER", unique=true, nullable=false)
    public Integer getIduser() {
        return this.iduser.get();
    }

    public void setIduser(Integer iduser) {
        this.iduser.set(iduser);
    }


    @Column(name="LOGIN", nullable=false, length=30)
    public String getLogin() {
        return this.login.get();
    }

    public void setLogin(String login) {
        this.login.set(login);
    }


    @Column(name="PASSWORD", nullable=false, length=150)
    public String getPassword() {
        return this.password.get();
    }

    public void setPassword(String password) {
        this.password.set(password);
    }


    @Override
    public String toString() {
        return getLogin();
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROFILE", nullable=false)
    public UserProfil getUserProfil() {
        return userProfil.get();
    }

    public ObjectProperty<UserProfil> userProfilProperty() {
        return userProfil;
    }

    public void setUserProfil(UserProfil userProfil) {
        this.userProfil.set(userProfil);
    }
}


